Repository AY2425S1-CS2103T-W08-1/tp, pull requests merged in 2024-10, with the labels that each got.

#53 Update delete student command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#57 Add Tut class
  src/main/java/seedu/address/model/tut/Tut.java
  src/test/java/seedu/address/model/student/TutTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: type.Task, priority.High

#54 Add Student data
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/TutorialClass.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Task, priority.High

#52 Add record student attendance feature
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tut/TutDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPresentDates.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutDate.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.Task, priority.High

#63 Add assignment features
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/CheckAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CheckAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAssignmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Epic, priority.High

#64 Delete assignment feature
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
Labels: type.Task, priority.High

#69 Add TutorialClass to Tut
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTutCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: type.Task, priority.High

#72 Add test cases for assignments
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/CheckAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAssignmentCommand.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CheckAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java
  src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/model/assignment/AssignmentListTest.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
Labels: type.Enhancement, priority.High

#76 Delete tutorial feature
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High

#77 Refine record student attendance feature
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/main/java/seedu/address/model/tut/TutDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPresentDates.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutDate.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/student/PresentDatesTest.java
  src/test/java/seedu/address/model/student/TutTest.java
  src/test/java/seedu/address/model/tut/TutDateTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Enhancement, priority.High

#79 Branch 1009 add tut
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTutCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/main/java/seedu/address/model/tut/TutDate.java
  src/main/java/seedu/address/model/tut/exceptions/TutDateNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedTut.java
  src/main/java/seedu/address/storage/JsonTutorialStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TutorialStorage.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/tut/TutDateTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: type.Task, priority.High

#81 Tutorials
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTutCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/student/TutorialClass.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/main/java/seedu/address/model/tut/TutDate.java
  src/main/java/seedu/address/model/tut/exceptions/TutDateNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedTut.java
  src/main/java/seedu/address/storage/JsonTutorialStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TutorialStorage.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/tut/TutDateTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: type.Enhancement, priority.High

#84 Refactor tutName
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/tut/Tut.java
  src/main/java/seedu/address/model/tut/TutName.java
  src/main/java/seedu/address/storage/JsonAdaptedTut.java
  src/test/java/seedu/address/logic/commands/AddTutCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: type.Enhancement, priority.High

#83 Refactor tutorial list
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddTutCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/model/tut/exceptions/DuplicateTutorialException.java
  src/main/java/seedu/address/storage/JsonAdaptedTut.java
  src/main/java/seedu/address/storage/JsonTutorialStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TutorialStorage.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialDateTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: type.Enhancement

#85 Fix tutorial.json bug
  src/main/java/seedu/address/model/tut/TutDate.java
  src/main/java/seedu/address/model/tut/TutName.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/storage/JsonSerializableTutorialList.java
  src/main/java/seedu/address/storage/JsonTutorialStorage.java
  src/test/data/JsonAssignmentStorageTest/invalidAssignments.json
  src/test/data/JsonAssignmentStorageTest/validAssignments.json
  src/test/java/seedu/address/model/tut/TutNameTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/storage/JsonAssignmentStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java
Labels: type.Bug

#89 Fix UI not responsive bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddTutCommand.java
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Bug, priority.High

#87 Change the command word
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Enhancement

#91 Fix tutDate hash code bug
  src/main/java/seedu/address/logic/parser/AttendCommandParser.java
  src/main/java/seedu/address/model/tut/TutDate.java
Labels: type.Bug

#92 Fix bug
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
Labels: type.Enhancement, type.Bug

#97 Update User Guide
  docs/UserGuide.md
  docs/images/AddAssignment.png
  docs/images/addStudent.png
  docs/images/addTutorial.png
  docs/images/assignmentCompletion.png
  docs/images/deleteAssignment.png
  docs/images/deleteStudent.png
  docs/images/listAssignment.png
  docs/images/markAssignment.png
  docs/images/recordAttendance.png
  docs/images/unmarkAssignment.png
Labels: type.Task, priority.High

#103 Delete feature bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/TutorialClass.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/model/tut/exceptions/NoTutorialException.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TutUtil.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: type.Bug, priority.High

#104 Add user guide structure
  docs/UserGuide.md
Labels: type.Task, priority.High

#107 Refine add command (parameters, readability)
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/AttendCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java
  src/test/java/seedu/address/storage/JsonTutorialStorageTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TutUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: type.Task, priority.High

#110 Debug delete tutorial feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/main/java/seedu/address/storage/JsonSerializableTutorialList.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java
Labels: type.Bug, priority.High

#109 Add Exist and None to Tutorial UML
  docs/diagrams/ModelClassDiagram2.puml
Labels: type.Task, priority.High

#120 Update UML diagram
  docs/diagrams/DeleteAssignmentActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Task, priority.High

#117 Arrange UML diagram to correct file
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Enhancement, type.Bug, priority.Medium

#125 Update user guide
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.High

#134 Add in handling of no tut for add stu
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Enhancement, priority.Medium

#130 Update user guide
  docs/UserGuide.md
Labels: priority.High

#127 Change all tutorialClass to tutorialId
  src/main/java/seedu/address/logic/commands/UnattendCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnattendCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: type.Bug, priority.High

#113 Add listTut Command
  build.gradle
  src/main/java/seedu/address/logic/commands/ListTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
Labels: priority.High

#118 Reimplement edit command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
Labels: type.Task, priority.High

#123 Reset id format
  docs/diagrams/AttendCommandSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTutCommand.java
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/UnattendCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonSerializableTutorialListTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TutUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/testutil/TypicalTutorials.java
Labels: type.Enhancement, priority.High

#139 Solve edit command bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#138 Fix ui and command bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UnattendCommand.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: type.Bug, priority.High

#142 Setup product website
  docs/index.md
Labels: type.Bug, priority.High

#143 Update title suffix
  docs/_markbind/layouts/default.md
  docs/site.json
Labels: type.Bug, priority.High

#150 Update help command url
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, alpha-bug

#151 Setup base url
  docs/site.json
Labels: type.Bug

#159 Modify the navigation bar
  docs/_markbind/layouts/default.md
Labels: type.Bug

#153 Update ug and command key word
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/logic/commands/UnattendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, priority.High

#173 Debug delete tutorial command
  src/main/java/seedu/address/model/tut/TutorialList.java
Labels: priority.High, alpha-bug

#166 Solve assignment bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/assignment/AssignmentListTest.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#174 Resolve edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Bug, priority.Medium, alpha-bug

#180 Sort present dates
  docs/UserGuide.md
  docs/diagrams/AttendCommandSequenceDiagram.puml
  docs/site.json
  src/main/java/seedu/address/logic/commands/AttendCommand.java
  src/main/java/seedu/address/logic/commands/UnattendCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/tut/TutDate.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AttendCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnattendCommandParserTest.java
  src/test/java/seedu/address/testutil/TutUtil.java
Labels: priority.Medium, severity.Low, alpha-bug

#181 Add installation guide to UG
  docs/UserGuide.md
  docs/images/startingGUI.png
  docs/img.png
Labels: type.Task, priority.High

#182 Debug developer guide display issue
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#183 Debug user guide faq navigation issue
  docs/_markbind/layouts/default.md
Labels: type.Bug, priority.High

#186 Add prefix for delete tutorial and assignment command
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddTutCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTutorialCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTutorialCommandParserTest.java
Labels: priority.Medium, severity.Low, alpha-bug

#187 Edit UI to fit layout
  docs/images/TrackMate.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/StudentProfile.java
  src/main/resources/images/TrackMate.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentProfile.fxml
  src/main/resources/view/logo.fxml
Labels: type.Task

#200 Change ui to light theme
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement
