Repository AY2425S1-CS2103T-W08-1/tp, pull requests merged in 2024-11, with the labels that each got.

#201 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureActivityDiagram.puml
  docs/diagrams/AddFeatureClassDiagram.puml
Labels: type.Documentation

#191 Update user guide on add command
  docs/UserGuide.md
Labels: type.Task, priority.Medium, type.Documentation

#188 Refine add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/student/StudentId.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: type.Bug, priority.Medium, alpha-bug

#199 Update UI for student cards and help window
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CheckAssignmentCommand.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/commands/CheckAssignmentCommandTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Enhancement, priority.High

#195 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
Labels: priority.High, type.Documentation

#203 Bug fix#170
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/parser/AddTutorialCommandParserTest.java
Labels: severity.Low, alpha-bug

#211 User guide update (glossary & minor error)
  docs/UserGuide.md
Labels: alpha-bug, type.Documentation

#194 AddTutorialSequenceDiagram
  docs/diagrams/AddTutorialSequenceDiagram.puml
Labels: type.Documentation

#248 Fix documentation flaws
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateAssignmentActivityDiagram.puml
  docs/site.json
Labels: priority.High, type.Documentation

#225 Remove unwanted println
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: type.Bug, severity.VeryLow

#227 Remove da statement from DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#254 Update the header logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/track_mate_empty_background.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, alpha-bug

#253 Solve alpha bug for Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddFeatureActivityDiagram.puml
  docs/diagrams/AddFeatureClassDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: alpha-bug, type.Documentation

#255 Solve bug on student selection
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/StudentProfile.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#252 Debug on delete command and user guide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, alpha-bug, type.Documentation

#258 Update developer guide delete format
  docs/DeveloperGuide.md
Labels: priority.Medium, alpha-bug, type.Documentation

#260 Update user guide command format
  docs/UserGuide.md
Labels: priority.Medium, alpha-bug, type.Documentation

#261 Debug result display for delete assignment
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/AssignmentList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/assignment/AssignmentListTest.java
Labels: priority.High, alpha-bug

#263 Modify result displayed for delete tutorial
  src/main/java/seedu/address/logic/commands/DeleteTutorialCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tut/Tutorial.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/AttendCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTutorialCommandTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
  src/test/java/seedu/address/model/tut/TutorialTest.java
Labels: type.Enhancement

#262 Update markbind navigation
  docs/_markbind/layouts/default.md
Labels: severity.High, alpha-bug

#264 Change diagrams sizes
  docs/DeveloperGuide.md
Labels: alpha-bug, type.Documentation

#269 User Guide update
  docs/UserGuide.md
Labels: type.Documentation

#267 Update README for website
  docs/UserGuide.md
  docs/index.md
Labels: type.Documentation

#265 Update UserGuide.md
  docs/UserGuide.md
Labels: alpha-bug, type.Documentation

#270 FixUGBug
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#272 Update UI image
  docs/images/TrackMateUi.png
  docs/index.md
Labels: priority.High, severity.High, alpha-bug, type.Documentation

#273 Update Ui displayed in docs
  docs/images/TrackMateUi.png
Labels: type.Bug, priority.Medium

#274 Update glossary in user guide
  docs/UserGuide.md
Labels: type.Documentation

#275 Update find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Enhancement, severity.Medium

#276 Update user guide
  docs/UserGuide.md
Labels: severity.Medium, type.Documentation

#277 Update find command for UG
  docs/UserGuide.md
Labels: type.Documentation

#278 Update details in UG
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#371 Fix PE dry run bugs
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AttendCommandSequenceDiagram.puml
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/student/Student.java
Labels: type.Bug, severity.High, type.Documentation

#372 Debug PE documentation link
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.Low, type.Documentation

#374 Resolve documentation bug
  docs/UserGuide.md
  docs/diagrams/DeleteAssignmentActivityDiagram.puml
  docs/images/startingGUI.png
Labels: priority.Medium, severity.Low, type.Documentation

#373 Solve command functionality bug & documentation bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: severity.Medium, alpha-bug, type.Documentation

#381 Fix edit bug related to mark attendance
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/PresentDates.java
  src/main/java/seedu/address/model/tut/TutDate.java
Labels: type.Bug, priority.Medium

#375 Remove unnecessary comments
  src/test/java/seedu/address/MainAppTest.java
Labels: type.Enhancement

#380 Debug delete tutorial command
  src/main/java/seedu/address/model/tut/TutorialList.java
Labels: type.Bug, priority.High, severity.Low

#382 Update UG for assignment
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img_1.png
Labels: type.Documentation

#377 Fix empty assignment issue
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/CheckAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkAssignmentCommandParser.java
  src/test/java/seedu/address/logic/parser/AddAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CheckAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandPaserTest.java
  src/test/java/seedu/address/logic/parser/MarkAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAssignmentCommandParserTest.java
Labels: type.Bug, severity.Low

#384 Update edit command in UG
  docs/UserGuide.md
Labels: type.Documentation

#388 Fix bugs3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tut/TutorialList.java
  src/main/java/seedu/address/model/tut/exceptions/TutNotFoundException.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tut/TutorialListTest.java
Labels: type.Documentation

#391 Fix UI display typo
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/student/StudentId.java
Labels: type.Bug, priority.Medium

#390 Explain the legal name restriction in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#392 Debug the documentation error
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#393 Review and update user guide
  docs/UserGuide.md
Labels: type.Documentation

#394 Debug setting up page
  docs/SettingUp.md
Labels: type.Bug, type.Documentation

#395 Debug on about us
  docs/AboutUs.md
Labels: type.Bug, severity.VeryLow, type.Documentation

#397 Update user guide
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#398 Fix developer guide bug
  docs/DeveloperGuide.md
Labels: severity.High, type.Documentation

#401 Enhance code quality
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/TutorialId.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
Labels: type.Documentation

#402 Enhance and refactor documentation
  docs/DeveloperGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: type.Enhancement, type.Documentation

#404 Fix attendance date format bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, severity.Medium

#406 Update DG diagrams
  docs/diagrams/AddTutorialSequenceDiagram.puml
Labels: type.Bug, type.Documentation

#408 Fix developer guide bug
  docs/DeveloperGuide.md
Labels: type.Documentation
